id = "paperclip01"

bind = "0.0.0.0:8004"
grpc_bind = "0.0.0.0:7004"

nexus_addr = "localhost:7001"

preferred_destination = 1

[workers]
files_deletion = 4
files_analyze = 4

[debug]
database = false
print_routes = false

[performance]
file_chunk_size = 26214400

[[destinations]]
type = "local"
path = "uploads"
[[destinations]]
type = "local"
path = "uploads/permanent"
access_baseurl = "http://192.168.50.133:8004"
image_proxy_baseurl = "https://io.sn.solsynth.dev"

[traffic]
maximum_size = 20971520
minimum_size = 1048576

[security]
internal_public_key = "keys/internal_public_key.pem"

[payment]
discount = 52428800
